name: CI/CD Pipeline

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches: [ main ]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7-dind

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and Push workload Frontend Docker image 
        run: |
          cd app
          TAG=${{ github.run_number }}
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:$TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:$TAG

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Fill in the new image ID in the ECS task definition
        run: |
          cd .github/ecs
          TAG=${{ github.run_number }}
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:$TAG"
          jq --arg IMAGE "$IMAGE" '.containerDefinitions[0].image=$IMAGE' ecs-task-def.json > new-task-def.json

      - name: Fill in the new image ID in the ECS task definition
        run: |
          cd .github/ecs
          TAG=${{ github.run_number }}
          IMAGE="${{ secrets.DOCKERHUB_USERNAME }}/simpletimeservice:$TAG"

          jq --arg IMAGE "$IMAGE" '
            .containerDefinitions[0].image = $IMAGE |
            del(.compatibilities, .registeredAt, .registeredBy, .requiresAttributes, .revision, .status, .taskDefinitionArn)
          ' ecs-task-def.json > new-task-def.json
          echo "Generated task definition:"
          cat new-task-def.json

      - name: Register Task Definition
        id: taskdef
        run: |
          cd .github/ecs
          TASK_DEF_ARN=$(aws ecs register-task-definition \
            --cli-input-json file://new-task-def.json \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "TASK_DEF_ARN=$TASK_DEF_ARN" >> $GITHUB_OUTPUT